[project]
name = "loltest"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
